<?php

namespace ContainerR1d8GZW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ELSGQjKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eLSGQjK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eLSGQjK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\StudentController::addStudent' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UsersController::delete' => ['privates', '.service_locator.2i2ZwV_', 'get_ServiceLocator_2i2ZwVService', true],
            'App\\Controller\\UsersController::edit' => ['privates', '.service_locator.2i2ZwV_', 'get_ServiceLocator_2i2ZwVService', true],
            'App\\Controller\\UsersController::index' => ['privates', '.service_locator.eBE7AIr', 'get_ServiceLocator_EBE7AIrService', true],
            'App\\Controller\\UsersController::new' => ['privates', '.service_locator.eBE7AIr', 'get_ServiceLocator_EBE7AIrService', true],
            'App\\Controller\\UsersController::show' => ['privates', '.service_locator.Sgq.tmb', 'get_ServiceLocator_Sgq_TmbService', true],
            'App\\Controller\\UsersController::show1' => ['privates', '.service_locator.Sgq.tmb', 'get_ServiceLocator_Sgq_TmbService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\StudentController:addStudent' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UsersController:delete' => ['privates', '.service_locator.2i2ZwV_', 'get_ServiceLocator_2i2ZwVService', true],
            'App\\Controller\\UsersController:edit' => ['privates', '.service_locator.2i2ZwV_', 'get_ServiceLocator_2i2ZwVService', true],
            'App\\Controller\\UsersController:index' => ['privates', '.service_locator.eBE7AIr', 'get_ServiceLocator_EBE7AIrService', true],
            'App\\Controller\\UsersController:new' => ['privates', '.service_locator.eBE7AIr', 'get_ServiceLocator_EBE7AIrService', true],
            'App\\Controller\\UsersController:show' => ['privates', '.service_locator.Sgq.tmb', 'get_ServiceLocator_Sgq_TmbService', true],
            'App\\Controller\\UsersController:show1' => ['privates', '.service_locator.Sgq.tmb', 'get_ServiceLocator_Sgq_TmbService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\StudentController::addStudent' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UsersController::delete' => '?',
            'App\\Controller\\UsersController::edit' => '?',
            'App\\Controller\\UsersController::index' => '?',
            'App\\Controller\\UsersController::new' => '?',
            'App\\Controller\\UsersController::show' => '?',
            'App\\Controller\\UsersController::show1' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\StudentController:addStudent' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UsersController:delete' => '?',
            'App\\Controller\\UsersController:edit' => '?',
            'App\\Controller\\UsersController:index' => '?',
            'App\\Controller\\UsersController:new' => '?',
            'App\\Controller\\UsersController:show' => '?',
            'App\\Controller\\UsersController:show1' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
