<?php

namespace ContainerJ2nhxqb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7uvbfUiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7uvbfUi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7uvbfUi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FournisseurController::delete' => ['privates', '.service_locator.CTY4JvY', 'get_ServiceLocator_CTY4JvYService', true],
            'App\\Controller\\FournisseurController::edit' => ['privates', '.service_locator.CTY4JvY', 'get_ServiceLocator_CTY4JvYService', true],
            'App\\Controller\\FournisseurController::index' => ['privates', '.service_locator.Jhh.C5S', 'get_ServiceLocator_Jhh_C5SService', true],
            'App\\Controller\\FournisseurController::new' => ['privates', '.service_locator.Jhh.C5S', 'get_ServiceLocator_Jhh_C5SService', true],
            'App\\Controller\\FournisseurController::show' => ['privates', '.service_locator.NOLKZxq', 'get_ServiceLocator_NOLKZxqService', true],
            'App\\Controller\\MaterielControllerBackController::affichage' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielControllerBackController::delete' => ['privates', '.service_locator.VFPmG3I', 'get_ServiceLocator_VFPmG3IService', true],
            'App\\Controller\\MaterielControllerBackController::edit' => ['privates', '.service_locator.VFPmG3I', 'get_ServiceLocator_VFPmG3IService', true],
            'App\\Controller\\MaterielControllerBackController::index' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielControllerBackController::new' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielControllerBackController::show' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\FournisseurController:delete' => ['privates', '.service_locator.CTY4JvY', 'get_ServiceLocator_CTY4JvYService', true],
            'App\\Controller\\FournisseurController:edit' => ['privates', '.service_locator.CTY4JvY', 'get_ServiceLocator_CTY4JvYService', true],
            'App\\Controller\\FournisseurController:index' => ['privates', '.service_locator.Jhh.C5S', 'get_ServiceLocator_Jhh_C5SService', true],
            'App\\Controller\\FournisseurController:new' => ['privates', '.service_locator.Jhh.C5S', 'get_ServiceLocator_Jhh_C5SService', true],
            'App\\Controller\\FournisseurController:show' => ['privates', '.service_locator.NOLKZxq', 'get_ServiceLocator_NOLKZxqService', true],
            'App\\Controller\\MaterielControllerBackController:affichage' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielControllerBackController:delete' => ['privates', '.service_locator.VFPmG3I', 'get_ServiceLocator_VFPmG3IService', true],
            'App\\Controller\\MaterielControllerBackController:edit' => ['privates', '.service_locator.VFPmG3I', 'get_ServiceLocator_VFPmG3IService', true],
            'App\\Controller\\MaterielControllerBackController:index' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielControllerBackController:new' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielControllerBackController:show' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\FournisseurController::delete' => '?',
            'App\\Controller\\FournisseurController::edit' => '?',
            'App\\Controller\\FournisseurController::index' => '?',
            'App\\Controller\\FournisseurController::new' => '?',
            'App\\Controller\\FournisseurController::show' => '?',
            'App\\Controller\\MaterielControllerBackController::affichage' => '?',
            'App\\Controller\\MaterielControllerBackController::delete' => '?',
            'App\\Controller\\MaterielControllerBackController::edit' => '?',
            'App\\Controller\\MaterielControllerBackController::index' => '?',
            'App\\Controller\\MaterielControllerBackController::new' => '?',
            'App\\Controller\\MaterielControllerBackController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FournisseurController:delete' => '?',
            'App\\Controller\\FournisseurController:edit' => '?',
            'App\\Controller\\FournisseurController:index' => '?',
            'App\\Controller\\FournisseurController:new' => '?',
            'App\\Controller\\FournisseurController:show' => '?',
            'App\\Controller\\MaterielControllerBackController:affichage' => '?',
            'App\\Controller\\MaterielControllerBackController:delete' => '?',
            'App\\Controller\\MaterielControllerBackController:edit' => '?',
            'App\\Controller\\MaterielControllerBackController:index' => '?',
            'App\\Controller\\MaterielControllerBackController:new' => '?',
            'App\\Controller\\MaterielControllerBackController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
