<?php

namespace ContainerXQBxUGt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XCTlhpoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xCTlhpo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xCTlhpo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'materiels' => ['privates', '.errored..service_locator.xCTlhpo.App\\Entity\\Materiel', NULL, 'Cannot autowire service ".service_locator.xCTlhpo": it references class "App\\Entity\\Materiel" but no such service exists.'],
        ], [
            'materiels' => 'App\\Entity\\Materiel',
        ]);
    }
}
