<?php

namespace ContainerXQBxUGt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VFPmG3IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VFPmG3I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VFPmG3I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'materiel' => ['privates', '.errored..service_locator.VFPmG3I.App\\Entity\\Materiel', NULL, 'Cannot autowire service ".service_locator.VFPmG3I": it references class "App\\Entity\\Materiel" but no such service exists.'],
            'materielRepository' => ['privates', 'App\\Repository\\MaterielRepository', 'getMaterielRepositoryService', true],
        ], [
            'materiel' => 'App\\Entity\\Materiel',
            'materielRepository' => 'App\\Repository\\MaterielRepository',
        ]);
    }
}
