<?php

namespace ContainerXQBxUGt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VFPmG3I.App\Entity\Materiel' shared service.
     *
     * @return \App\Entity\Materiel
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VFPmG3I": it references class "App\\Entity\\Materiel" but no such service exists.');
    }
}
