<?php

namespace ContainerGxmokVG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFournisseurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CTY4JvY.App\Entity\Fournisseur' shared service.
     *
     * @return \App\Entity\Fournisseur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CTY4JvY": it references class "App\\Entity\\Fournisseur" but no such service exists.');
    }
}
