<?php

namespace ContainerS59mGiD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BrqgTzVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.brqgTzV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.brqgTzV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'user' => ['privates', '.errored.IZlwMM1', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::show()": the $user argument is type-hinted with the non-existent class or interface: "App\\Entity\\User".'],
        ], [
            'user' => '?',
        ]);
    }
}
