<?php

namespace ContainerZlc1HQM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VKX7spEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VKX7spE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VKX7spE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userRepository' => ['privates', '.errored.5_o4iSm', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::new()": the $userRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\UserRepository".'],
        ], [
            'userRepository' => '?',
        ]);
    }
}
