<?php

namespace ContainerXDkySC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DxUu3frService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dxUu3fr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dxUu3fr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EventController::delete' => ['privates', '.service_locator.fFHahJ8', 'get_ServiceLocator_FFHahJ8Service', true],
            'App\\Controller\\EventController::edit' => ['privates', '.service_locator.fFHahJ8', 'get_ServiceLocator_FFHahJ8Service', true],
            'App\\Controller\\EventController::index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Controller\\EventController::new' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Controller\\EventController::show' => ['privates', '.service_locator.wLYTQQR', 'get_ServiceLocator_WLYTQQRService', true],
            'App\\Controller\\StudentController::addStudent' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\EventController:delete' => ['privates', '.service_locator.fFHahJ8', 'get_ServiceLocator_FFHahJ8Service', true],
            'App\\Controller\\EventController:edit' => ['privates', '.service_locator.fFHahJ8', 'get_ServiceLocator_FFHahJ8Service', true],
            'App\\Controller\\EventController:index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Controller\\EventController:new' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Controller\\EventController:show' => ['privates', '.service_locator.wLYTQQR', 'get_ServiceLocator_WLYTQQRService', true],
            'App\\Controller\\StudentController:addStudent' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\EventController::delete' => '?',
            'App\\Controller\\EventController::edit' => '?',
            'App\\Controller\\EventController::index' => '?',
            'App\\Controller\\EventController::new' => '?',
            'App\\Controller\\EventController::show' => '?',
            'App\\Controller\\StudentController::addStudent' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EventController:delete' => '?',
            'App\\Controller\\EventController:edit' => '?',
            'App\\Controller\\EventController:index' => '?',
            'App\\Controller\\EventController:new' => '?',
            'App\\Controller\\EventController:show' => '?',
            'App\\Controller\\StudentController:addStudent' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
