<?php

namespace ContainerDkhEI41;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WLYTQQRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wLYTQQR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wLYTQQR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator.wLYTQQR.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.wLYTQQR": it references class "App\\Entity\\Event" but no such service exists.'],
        ], [
            'event' => 'App\\Entity\\Event',
        ]);
    }
}
