<?php

namespace ContainerUQ1Tx1v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__MtIOj8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..MtIOj8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..MtIOj8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ReclamationController::delete' => ['privates', '.service_locator.i7JOFAN', 'get_ServiceLocator_I7JOFANService', true],
            'App\\Controller\\ReclamationController::edit' => ['privates', '.service_locator.i7JOFAN', 'get_ServiceLocator_I7JOFANService', true],
            'App\\Controller\\ReclamationController::index' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController::new' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController::show' => ['privates', '.service_locator.iq_16Ky', 'get_ServiceLocator_Iq16KyService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\StudentController::addStudent' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.3Lz30ht', 'get_ServiceLocator_3Lz30htService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.h6_htL7', 'get_ServiceLocator_H6HtL7Service', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.bAgRiHP', 'get_ServiceLocator_BAgRiHPService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.VKX7spE', 'get_ServiceLocator_VKX7spEService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.brqgTzV', 'get_ServiceLocator_BrqgTzVService', true],
            'App\\Controller\\UsersController::delete' => ['privates', '.service_locator.2i2ZwV_', 'get_ServiceLocator_2i2ZwVService', true],
            'App\\Controller\\UsersController::edit' => ['privates', '.service_locator.2i2ZwV_', 'get_ServiceLocator_2i2ZwVService', true],
            'App\\Controller\\UsersController::index' => ['privates', '.service_locator.zxHu7U5', 'get_ServiceLocator_ZxHu7U5Service', true],
            'App\\Controller\\UsersController::new' => ['privates', '.service_locator.eBE7AIr', 'get_ServiceLocator_EBE7AIrService', true],
            'App\\Controller\\UsersController::show' => ['privates', '.service_locator.Sgq.tmb', 'get_ServiceLocator_Sgq_TmbService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ReclamationController:delete' => ['privates', '.service_locator.i7JOFAN', 'get_ServiceLocator_I7JOFANService', true],
            'App\\Controller\\ReclamationController:edit' => ['privates', '.service_locator.i7JOFAN', 'get_ServiceLocator_I7JOFANService', true],
            'App\\Controller\\ReclamationController:index' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController:new' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController:show' => ['privates', '.service_locator.iq_16Ky', 'get_ServiceLocator_Iq16KyService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\StudentController:addStudent' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.3Lz30ht', 'get_ServiceLocator_3Lz30htService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.h6_htL7', 'get_ServiceLocator_H6HtL7Service', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.bAgRiHP', 'get_ServiceLocator_BAgRiHPService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.VKX7spE', 'get_ServiceLocator_VKX7spEService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.brqgTzV', 'get_ServiceLocator_BrqgTzVService', true],
            'App\\Controller\\UsersController:delete' => ['privates', '.service_locator.2i2ZwV_', 'get_ServiceLocator_2i2ZwVService', true],
            'App\\Controller\\UsersController:edit' => ['privates', '.service_locator.2i2ZwV_', 'get_ServiceLocator_2i2ZwVService', true],
            'App\\Controller\\UsersController:index' => ['privates', '.service_locator.zxHu7U5', 'get_ServiceLocator_ZxHu7U5Service', true],
            'App\\Controller\\UsersController:new' => ['privates', '.service_locator.eBE7AIr', 'get_ServiceLocator_EBE7AIrService', true],
            'App\\Controller\\UsersController:show' => ['privates', '.service_locator.Sgq.tmb', 'get_ServiceLocator_Sgq_TmbService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ReclamationController::delete' => '?',
            'App\\Controller\\ReclamationController::edit' => '?',
            'App\\Controller\\ReclamationController::index' => '?',
            'App\\Controller\\ReclamationController::new' => '?',
            'App\\Controller\\ReclamationController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\StudentController::addStudent' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UsersController::delete' => '?',
            'App\\Controller\\UsersController::edit' => '?',
            'App\\Controller\\UsersController::index' => '?',
            'App\\Controller\\UsersController::new' => '?',
            'App\\Controller\\UsersController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ReclamationController:delete' => '?',
            'App\\Controller\\ReclamationController:edit' => '?',
            'App\\Controller\\ReclamationController:index' => '?',
            'App\\Controller\\ReclamationController:new' => '?',
            'App\\Controller\\ReclamationController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\StudentController:addStudent' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UsersController:delete' => '?',
            'App\\Controller\\UsersController:edit' => '?',
            'App\\Controller\\UsersController:index' => '?',
            'App\\Controller\\UsersController:new' => '?',
            'App\\Controller\\UsersController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
