<?php

namespace ContainerCMxmR1X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_IZlwMM1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.IZlwMM1' shared service.
     *
     * @return \App\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\UserController::show()": the $user argument is type-hinted with the non-existent class or interface: "App\\Entity\\User".');
    }
}
