<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7wnAQhn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7wnAQhn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7wnAQhn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7wnAQhn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7wnAQhn\App_KernelDevDebugContainer([
    'container.build_hash' => '7wnAQhn',
    'container.build_id' => '1f6acab7',
    'container.build_time' => 1678276451,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7wnAQhn');
