<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG5tR6Zp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG5tR6Zp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG5tR6Zp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG5tR6Zp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG5tR6Zp\App_KernelDevDebugContainer([
    'container.build_hash' => 'G5tR6Zp',
    'container.build_id' => 'b38b8f97',
    'container.build_time' => 1678188676,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG5tR6Zp');
