<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_fournisseur_index' => [[], ['_controller' => 'App\\Controller\\FournisseurController::index'], [], [['text', '/fournisseur/']], [], [], []],
    'app_fournisseur_new' => [[], ['_controller' => 'App\\Controller\\FournisseurController::new'], [], [['text', '/fournisseur/new']], [], [], []],
    'app_fournisseur_show' => [['id_f'], ['_controller' => 'App\\Controller\\FournisseurController::show'], [], [['variable', '/', '[^/]++', 'id_f', true], ['text', '/fournisseur']], [], [], []],
    'app_fournisseur_edit' => [['id_f'], ['_controller' => 'App\\Controller\\FournisseurController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id_f', true], ['text', '/fournisseur']], [], [], []],
    'app_fournisseur_delete' => [['id_f'], ['_controller' => 'App\\Controller\\FournisseurController::delete'], [], [['variable', '/', '[^/]++', 'id_f', true], ['text', '/fournisseur']], [], [], []],
    'app_materiel_controller_back_index' => [[], ['_controller' => 'App\\Controller\\MaterielControllerBackController::affichage'], [], [['text', '/materiel/afficher']], [], [], []],
    'app_materiel_controller_back_new' => [[], ['_controller' => 'App\\Controller\\MaterielControllerBackController::new'], [], [['text', '/materiel/new']], [], [], []],
    'app_materiel_controller_back_show' => [[], ['_controller' => 'App\\Controller\\MaterielControllerBackController::show'], [], [['text', '/materiel/show']], [], [], []],
    'app_materiel_controller_back_edit' => [['id_mat'], ['_controller' => 'App\\Controller\\MaterielControllerBackController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id_mat', true], ['text', '/materiel']], [], [], []],
    'app_materiel_controller_back_delete' => [['id_mat'], ['_controller' => 'App\\Controller\\MaterielControllerBackController::delete'], [], [['variable', '/', '[^/]++', 'id_mat', true], ['text', '/materiel']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
